### ISSUE TITLE
Update Products panel on bot creation

### ISSUE THREAD

**Issue by matbenitez** [Superalgos/CanvasApp#2]
The list is not updated unless you refresh the entire page:
![image](https://user-images.githubusercontent.com/34651529/48970492-899e3500-efeb-11e8-9f3b-9543749887d0.png)

**Comment by Luis-Fernando-Molina** [comment]
This will be solve once the Financial Beings module is there. It is not worth to continue patching the current stuff against the Ecosystem file.
