### ISSUE TITLE
Check this error

### ISSUE THREAD

**Issue by matbenitez** [Superalgos/CanvasApp#3]
CloudVM : [ERROR] checkForChangesInBotCode -> err.message = newUserBot is not defined

![image](https://user-images.githubusercontent.com/34651529/48970608-e51cf280-efec-11e8-922d-c46d5daa1e2a.png)

**Comment by Luis-Fernando-Molina** [comment]
Many things have changed since this error was reported. No way to reproduce it today. Closing it to clean up the issue list.
