### ISSUE TITLE
Issue when changing the scale

### ISSUE THREAD

**Issue by matbenitez** [Superalgos/CanvasApp#36]
Selecting the trading simulation, on the 15-min time period and then using the right scale to adjust the view, all components moves to the top.

![image](https://user-images.githubusercontent.com/34651529/56472079-91de8d00-6430-11e9-8a8b-575b8b2f1891.png)

**Comment by Luis-Fernando-Molina** [comment]
@matbenitez many things have changed related to the scaling in the last few days... is this still happening?

At the latest version is working fine for me:

![image](https://user-images.githubusercontent.com/9479367/56688386-e4da6d80-66d8-11e9-8cee-5a107793ea90.png)

**Comment by matbenitez** [comment]
Fixed!

**Comment by matbenitez** [comment]
Checked, and still happening.

**Comment by Luis-Fernando-Molina** [comment]
BUG Fixed
