### ISSUE TITLE
Failed to load charts

### ISSUE THREAD

**Issue by matbenitez** [Superalgos/CanvasApp#37]
There is an intermittent error loading charts on the following condition: refresh the webpage on the browser, select charts. This is more frequent with a slow internet connection.

![image](https://user-images.githubusercontent.com/34651529/56472130-17623d00-6431-11e9-95bd-860c763d7bfc.png)

**Comment by Luis-Fernando-Molina** [comment]
@matbenitez is this still hapening? Any way to reproduce it?
